#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${PWD}"
INSTALL_ROOT="${AILANG_INSTALL_ROOT:-${HOME}/.ailang}"

usage() {
  cat <<'EOF'
Usage:
  scripts/select-toolchain.sh <version|local> [project-dir]
  scripts/select-toolchain.sh --clear [project-dir]
  scripts/select-toolchain.sh --show [project-dir]
  scripts/select-toolchain.sh --list

Writes a project-local ailang-toolchain.toml file. Shims generated by
scripts/update-local-toolchain.sh read this file before falling back to
~/.ailang/current. The special value `local` selects ~/.ailang/local.

Examples:
  scripts/select-toolchain.sh local ../AiVectra
  scripts/select-toolchain.sh 0.0.1-alpha.15 .
  scripts/select-toolchain.sh --clear .
EOF
}

if [[ $# -eq 0 ]]; then
  usage >&2
  exit 2
fi

case "$1" in
  --list)
    if [[ -d "${INSTALL_ROOT}/local" ]]; then
      echo "local"
    fi
    if [[ -d "${INSTALL_ROOT}/toolchains" ]]; then
      find "${INSTALL_ROOT}/toolchains" -mindepth 1 -maxdepth 1 \( -type d -o -type l \) -exec basename {} \; | sort | grep -v '^local$' || true
    fi
    exit 0
    ;;
  --show)
    PROJECT_DIR="${2:-${PWD}}"
    if [[ -f "${PROJECT_DIR}/ailang-toolchain.toml" ]]; then
      sed -n 's/^[[:space:]]*version[[:space:]]*=[[:space:]]*"\([^"]*\)".*/\1/p' "${PROJECT_DIR}/ailang-toolchain.toml" | head -n 1
    elif [[ -f "${PROJECT_DIR}/.ailang-toolchain" ]]; then
      sed -n '1{s/^[[:space:]]*//;s/[[:space:]]*$//;p;}' "${PROJECT_DIR}/.ailang-toolchain"
    else
      echo "(current)"
    fi
    exit 0
    ;;
  --clear)
    PROJECT_DIR="${2:-${PWD}}"
    rm -f "${PROJECT_DIR}/ailang-toolchain.toml" "${PROJECT_DIR}/.ailang-toolchain"
    echo "Cleared AiLang toolchain selection in ${PROJECT_DIR}"
    exit 0
    ;;
  -h|--help)
    usage
    exit 0
    ;;
esac

TOOLCHAIN="$1"
PROJECT_DIR="${2:-${PWD}}"

if [[ ! -d "${PROJECT_DIR}" ]]; then
  echo "project directory not found: ${PROJECT_DIR}" >&2
  exit 1
fi

if [[ "${TOOLCHAIN}" == "local" ]]; then
  EXPECTED="${INSTALL_ROOT}/local"
else
  EXPECTED="${INSTALL_ROOT}/toolchains/${TOOLCHAIN}"
fi

if [[ ! -d "${EXPECTED}" ]]; then
  echo "warning: toolchain is not installed yet: ${EXPECTED}" >&2
fi

cat > "${PROJECT_DIR}/ailang-toolchain.toml" <<EOF
[toolchain]
version = "${TOOLCHAIN}"
EOF

echo "Selected AiLang toolchain '${TOOLCHAIN}' for ${PROJECT_DIR}"
