#include "aivm_syscall_contracts.h"

#include <string.h>

static const AivmSyscallContract Contracts[] = {
    { 0U, "sys.net_listen", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 1U, "sys.net_listen_tls", 3U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 2U, "sys.net_accept", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 3U, "sys.net_readHeaders", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 4U, "sys.net_write", 2U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 5U, "sys.net_close", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 6U, "sys.console_write", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 7U, "sys.console_writeLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 8U, "sys.console_readLine", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 9U, "sys.console_readAllStdin", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 10U, "sys.console_writeErrLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 16U, "sys.stdout_writeLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 11U, "sys.process_cwd", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 12U, "sys.process_envGet", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 18U, "sys.process_argv", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 28U, "sys.platform", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 29U, "sys.arch", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 30U, "sys.os_version", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 31U, "sys.runtime", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 13U, "sys.time_nowUnixMs", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 14U, "sys.time_monotonicMs", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 15U, "sys.time_sleepMs", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 17U, "sys.proc_exit", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 19U, "sys.fs_readFile", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 20U, "sys.fs_fileExists", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 21U, "sys.fs_readDir", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 22U, "sys.fs_stat", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 23U, "sys.fs_pathExists", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 24U, "sys.fs_writeFile", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 25U, "sys.fs_makeDir", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 37U, "sys.crypto_base64Encode", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 38U, "sys.crypto_base64Decode", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 39U, "sys.crypto_sha1", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 40U, "sys.crypto_sha256", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 41U, "sys.crypto_hmacSha256", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 42U, "sys.crypto_randomBytes", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 27U, "sys.net_tcpConnect", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 32U, "sys.net_tcpListen", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 33U, "sys.net_tcpListenTls", 4U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 34U, "sys.net_tcpAccept", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 35U, "sys.net_tcpRead", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 36U, "sys.net_tcpWrite", 2U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 61U, "sys.net_tcpConnectTls", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 62U, "sys.net_tcpConnectStart", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 63U, "sys.net_tcpConnectTlsStart", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 64U, "sys.net_tcpReadStart", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 65U, "sys.net_tcpWriteStart", 2U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 66U, "sys.net_asyncPoll", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 67U, "sys.net_asyncAwait", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 68U, "sys.net_asyncCancel", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 69U, "sys.net_asyncResultInt", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 70U, "sys.net_asyncResultString", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 71U, "sys.net_asyncError", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 43U, "sys.net_udpBind", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 44U, "sys.net_udpRecv", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 45U, "sys.net_udpSend", 4U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 46U, "sys.ui_createWindow", 3U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 47U, "sys.ui_beginFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 48U, "sys.ui_drawRect", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 49U, "sys.ui_drawText", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 50U, "sys.ui_endFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 51U, "sys.ui_pollEvent", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 52U, "sys.ui_present", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 53U, "sys.ui_closeWindow", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 54U, "sys.ui_drawLine", 7U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 55U, "sys.ui_drawEllipse", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 56U, "sys.ui_drawPath", 4U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 57U, "sys.ui_drawImage", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 58U, "sys.ui_getWindowSize", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 72U, "sys.ui_waitFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 73U, "sys.worker_start", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 74U, "sys.worker_poll", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 75U, "sys.worker_result", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 76U, "sys.worker_error", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 77U, "sys.worker_cancel", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 78U, "sys.debug_emit", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 79U, "sys.debug_mode", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 80U, "sys.debug_captureFrameBegin", 3U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 81U, "sys.debug_captureFrameEnd", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 82U, "sys.debug_captureDraw", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 83U, "sys.debug_captureInput", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 84U, "sys.debug_captureState", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 85U, "sys.debug_replayLoad", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 86U, "sys.debug_replayNext", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 87U, "sys.debug_assert", 3U, { AIVM_VAL_BOOL, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 88U, "sys.debug_artifactWrite", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 89U, "sys.debug_traceAsync", 3U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 26U, "sys.str_utf8ByteCount", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 59U, "sys.str_substring", 3U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 60U, "sys.str_remove", 3U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID }, AIVM_VAL_STRING }
};

static AivmContractStatus validate_contract(
    const AivmSyscallContract* contract,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    size_t arg_index;

    if (out_return_type != NULL) {
        *out_return_type = AIVM_VAL_VOID;
    }

    if (contract == NULL) {
        return AIVM_CONTRACT_ERR_UNKNOWN_TARGET;
    }

    if (contract->arg_count != arg_count) {
        return AIVM_CONTRACT_ERR_ARG_COUNT;
    }

    for (arg_index = 0U; arg_index < arg_count; arg_index += 1U) {
        if (args == NULL || args[arg_index].type != contract->arg_types[arg_index]) {
            return AIVM_CONTRACT_ERR_ARG_TYPE;
        }
    }

    if (out_return_type != NULL) {
        *out_return_type = contract->return_type;
    }
    return AIVM_CONTRACT_OK;
}

const AivmSyscallContract* aivm_syscall_contract_find_by_target(const char* target)
{
    size_t index;

    if (target == NULL) {
        return NULL;
    }

    for (index = 0U; index < (sizeof(Contracts) / sizeof(Contracts[0])); index += 1U) {
        if (strcmp(Contracts[index].target, target) == 0) {
            return &Contracts[index];
        }
    }

    return NULL;
}

const AivmSyscallContract* aivm_syscall_contract_find_by_id(uint32_t id)
{
    size_t index;
    for (index = 0U; index < (sizeof(Contracts) / sizeof(Contracts[0])); index += 1U) {
        if (Contracts[index].id == id) {
            return &Contracts[index];
        }
    }
    return NULL;
}

AivmContractStatus aivm_syscall_contract_validate(
    const char* target,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    const AivmSyscallContract* contract = aivm_syscall_contract_find_by_target(target);
    if (contract == NULL) {
        return AIVM_CONTRACT_ERR_UNKNOWN_TARGET;
    }
    return validate_contract(contract, args, arg_count, out_return_type);
}

AivmContractStatus aivm_syscall_contract_validate_id(
    uint32_t id,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    const AivmSyscallContract* contract = aivm_syscall_contract_find_by_id(id);
    if (contract == NULL) {
        if (out_return_type != NULL) {
            *out_return_type = AIVM_VAL_VOID;
        }
        return AIVM_CONTRACT_ERR_UNKNOWN_ID;
    }
    return validate_contract(contract, args, arg_count, out_return_type);
}

const char* aivm_contract_status_code(AivmContractStatus status)
{
    switch (status) {
        case AIVM_CONTRACT_OK:
            return "AIVMC000";
        case AIVM_CONTRACT_ERR_UNKNOWN_TARGET:
            return "AIVMC001";
        case AIVM_CONTRACT_ERR_ARG_COUNT:
            return "AIVMC002";
        case AIVM_CONTRACT_ERR_ARG_TYPE:
            return "AIVMC003";
        case AIVM_CONTRACT_ERR_UNKNOWN_ID:
            return "AIVMC004";
        default:
            return "AIVMC999";
    }
}

const char* aivm_contract_status_message(AivmContractStatus status)
{
    switch (status) {
        case AIVM_CONTRACT_OK:
            return "Syscall contract validation passed.";
        case AIVM_CONTRACT_ERR_UNKNOWN_TARGET:
            return "Syscall target was not found.";
        case AIVM_CONTRACT_ERR_ARG_COUNT:
            return "Syscall argument count was invalid.";
        case AIVM_CONTRACT_ERR_ARG_TYPE:
            return "Syscall argument type was invalid.";
        case AIVM_CONTRACT_ERR_UNKNOWN_ID:
            return "Syscall contract ID was not found.";
        default:
            return "Unknown syscall contract validation status.";
    }
}
