#include "sys/aivm_syscall_contracts.h"

#include <string.h>

static const AivmSyscallContract Contracts[] = {
    { 5U, "sys.net.tcp.close", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 6U, "sys.console.write", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 7U, "sys.console.writeLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 8U, "sys.console.readLine", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 9U, "sys.console.readAllStdin", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 10U, "sys.console.writeErrLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 16U, "sys.stdout.writeLine", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 11U, "sys.process.cwd", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 12U, "sys.process.env.get", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 18U, "sys.process.args", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 105U, "sys.process.spawn", 4U, { AIVM_VAL_STRING, AIVM_VAL_NODE, AIVM_VAL_STRING, AIVM_VAL_NODE, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 106U, "sys.process.wait", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 107U, "sys.process.kill", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 108U, "sys.process.stdout.read", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 109U, "sys.process.stderr.read", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 110U, "sys.process.poll", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 28U, "sys.platform", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 29U, "sys.arch", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 30U, "sys.os.version", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 31U, "sys.runtime", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 13U, "sys.time.nowUnixMs", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 14U, "sys.time.monotonicMs", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 15U, "sys.time.sleepMs", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 17U, "sys.process.exit", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 19U, "sys.fs.file.read", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 20U, "sys.fs.file.exists", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 21U, "sys.fs.dir.list", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 22U, "sys.fs.path.stat", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 23U, "sys.fs.path.exists", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 24U, "sys.fs.file.write", 2U, { AIVM_VAL_STRING, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 25U, "sys.fs.dir.create", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 103U, "sys.fs.file.delete", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 104U, "sys.fs.dir.delete", 2U, { AIVM_VAL_STRING, AIVM_VAL_BOOL, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 37U, "sys.crypto.base64Encode", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 38U, "sys.crypto.base64Decode", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 39U, "sys.crypto.sha1", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 40U, "sys.crypto.sha256", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 41U, "sys.crypto.hmacSha256", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 42U, "sys.crypto.randomBytes", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 27U, "sys.net.tcp.connect", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 32U, "sys.net.tcp.listen", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 33U, "sys.net.tcp.listenTls", 4U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 34U, "sys.net.tcp.accept", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 35U, "sys.net.tcp.read", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 36U, "sys.net.tcp.write", 2U, { AIVM_VAL_INT, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 61U, "sys.net.tcp.connectTls", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 62U, "sys.net.tcp.connectStart", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 63U, "sys.net.tcp.connectTlsStart", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 64U, "sys.net.tcp.readStart", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 65U, "sys.net.tcp.writeStart", 2U, { AIVM_VAL_INT, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 66U, "sys.net.async.poll", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 67U, "sys.net.async.await", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 68U, "sys.net.async.cancel", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 69U, "sys.net.async.resultInt", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 70U, "sys.net.async.resultBytes", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 71U, "sys.net.async.error", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 43U, "sys.net.udp.bind", 2U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 44U, "sys.net.udp.recv", 2U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 45U, "sys.net.udp.send", 4U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 46U, "sys.ui.createWindow", 3U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 47U, "sys.ui.beginFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 48U, "sys.ui.drawRect", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 49U, "sys.ui.drawText", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 50U, "sys.ui.endFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 51U, "sys.ui.pollEvent", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 52U, "sys.ui.present", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 53U, "sys.ui.closeWindow", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 54U, "sys.ui.drawLine", 7U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 55U, "sys.ui.drawEllipse", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 56U, "sys.ui.drawPath", 4U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 57U, "sys.ui.drawImage", 6U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 58U, "sys.ui.getWindowSize", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE },
    { 72U, "sys.ui.waitFrame", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 73U, "sys.worker.start", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 74U, "sys.worker.poll", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 75U, "sys.worker.result", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 76U, "sys.worker.error", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 77U, "sys.worker.cancel", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 78U, "sys.debug.emit", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 79U, "sys.debug.mode", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 80U, "sys.debug.captureFrameBegin", 3U, { AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 81U, "sys.debug.captureFrameEnd", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 82U, "sys.debug.captureDraw", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 83U, "sys.debug.captureInput", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 84U, "sys.debug.captureState", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 85U, "sys.debug.replayLoad", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 86U, "sys.debug.replayNext", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 87U, "sys.debug.assert", 3U, { AIVM_VAL_BOOL, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 88U, "sys.debug.artifactWrite", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BOOL },
    { 89U, "sys.debug.traceAsync", 3U, { AIVM_VAL_INT, AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_VOID },
    { 26U, "sys.str.utf8ByteCount", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 59U, "sys.str.substring", 3U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 60U, "sys.str.remove", 3U, { AIVM_VAL_STRING, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 111U, "sys.str.fromCodePoint", 1U, { AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 112U, "sys.str.decodeUnicodeHex4", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 113U, "sys.str.decodeUnicodeSurrogatePairHex4", 2U, { AIVM_VAL_STRING, AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 97U, "sys.bytes.length", 1U, { AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 98U, "sys.bytes.fromBase64", 1U, { AIVM_VAL_STRING, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 99U, "sys.bytes.toBase64", 1U, { AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 100U, "sys.bytes.at", 2U, { AIVM_VAL_BYTES, AIVM_VAL_INT, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_INT },
    { 101U, "sys.bytes.slice", 3U, { AIVM_VAL_BYTES, AIVM_VAL_INT, AIVM_VAL_INT, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 102U, "sys.bytes.concat", 2U, { AIVM_VAL_BYTES, AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_BYTES },
    { 114U, "sys.bytes.toUtf8String", 1U, { AIVM_VAL_BYTES, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_STRING },
    { 115U, "sys.debug.taskReclaimStats", 0U, { AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID, AIVM_VAL_VOID }, AIVM_VAL_NODE }
};

static AivmContractStatus validate_contract(
    const AivmSyscallContract* contract,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    size_t arg_index;

    if (out_return_type != NULL) {
        *out_return_type = AIVM_VAL_VOID;
    }

    if (contract == NULL) {
        return AIVM_CONTRACT_ERR_UNKNOWN_TARGET;
    }

    if (contract->arg_count != arg_count) {
        return AIVM_CONTRACT_ERR_ARG_COUNT;
    }

    for (arg_index = 0U; arg_index < arg_count; arg_index += 1U) {
        if (args == NULL || args[arg_index].type != contract->arg_types[arg_index]) {
            return AIVM_CONTRACT_ERR_ARG_TYPE;
        }
    }

    if (out_return_type != NULL) {
        *out_return_type = contract->return_type;
    }
    return AIVM_CONTRACT_OK;
}

const AivmSyscallContract* aivm_syscall_contract_find_by_target(const char* target)
{
    size_t index;

    if (target == NULL) {
        return NULL;
    }

    for (index = 0U; index < (sizeof(Contracts) / sizeof(Contracts[0])); index += 1U) {
        if (strcmp(Contracts[index].target, target) == 0) {
            return &Contracts[index];
        }
    }

    return NULL;
}

const AivmSyscallContract* aivm_syscall_contract_find_by_id(uint32_t id)
{
    size_t index;
    for (index = 0U; index < (sizeof(Contracts) / sizeof(Contracts[0])); index += 1U) {
        if (Contracts[index].id == id) {
            return &Contracts[index];
        }
    }
    return NULL;
}

AivmContractStatus aivm_syscall_contract_validate(
    const char* target,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    const AivmSyscallContract* contract = aivm_syscall_contract_find_by_target(target);
    if (contract == NULL) {
        return AIVM_CONTRACT_ERR_UNKNOWN_TARGET;
    }
    return validate_contract(contract, args, arg_count, out_return_type);
}

AivmContractStatus aivm_syscall_contract_validate_id(
    uint32_t id,
    const AivmValue* args,
    size_t arg_count,
    AivmValueType* out_return_type)
{
    const AivmSyscallContract* contract = aivm_syscall_contract_find_by_id(id);
    if (contract == NULL) {
        if (out_return_type != NULL) {
            *out_return_type = AIVM_VAL_VOID;
        }
        return AIVM_CONTRACT_ERR_UNKNOWN_ID;
    }
    return validate_contract(contract, args, arg_count, out_return_type);
}

const char* aivm_contract_status_code(AivmContractStatus status)
{
    switch (status) {
        case AIVM_CONTRACT_OK:
            return "AIVMC000";
        case AIVM_CONTRACT_ERR_UNKNOWN_TARGET:
            return "AIVMC001";
        case AIVM_CONTRACT_ERR_ARG_COUNT:
            return "AIVMC002";
        case AIVM_CONTRACT_ERR_ARG_TYPE:
            return "AIVMC003";
        case AIVM_CONTRACT_ERR_UNKNOWN_ID:
            return "AIVMC004";
        default:
            return "AIVMC999";
    }
}

const char* aivm_contract_status_message(AivmContractStatus status)
{
    switch (status) {
        case AIVM_CONTRACT_OK:
            return "Syscall contract validation passed.";
        case AIVM_CONTRACT_ERR_UNKNOWN_TARGET:
            return "Syscall target was not found.";
        case AIVM_CONTRACT_ERR_ARG_COUNT:
            return "Syscall argument count was invalid.";
        case AIVM_CONTRACT_ERR_ARG_TYPE:
            return "Syscall argument type was invalid.";
        case AIVM_CONTRACT_ERR_UNKNOWN_ID:
            return "Syscall contract ID was not found.";
        default:
            return "Unknown syscall contract validation status.";
    }
}
